Host debian
  User thehrz
  HostName debian.lan
  Port 2233
  IdentityFile ~/.ssh/thehrz_server

Host base-server
  User thehrz
  HostName base-server.lan
  Port 22

Host platform
  User thehrz
  HostName platform.lan
  Port 22

Host openwrt
  User root
  HostName openwrt.lan
  Port 22

Host mc-server
  User mc
  HostName mc-server.lan
  Port 2233
  IdentityFile ~/.ssh/thehrz_server

Host runner
  User thehrz
  HostName runner.lan
  Port 2233
  IdentityFile ~/.ssh/thehrz_server
