Host github.com
  Hostname ssh.github.com
  Port 443
  IdentityFile ~/.ssh/arixel

Host git.corehrz.ink
  HostName 42.121.163.17
  Port 22
  IdentityFile ~/.ssh/arixel

Host git.thehrz.net
  HostName 8.218.181.38
  Port 22
  IdentityFile ~/.ssh/thehrz

Host git.byprism.cn
  HostName 8.159.146.42
  Port 22
  IdentityFile ~/.ssh/byprism