Host vultr-tk-0
  user root
  HostName 202.182.113.74
  Port 22
  IdentityFile ~/.ssh/thehrz_server

Host hfbz-forum
  user root
  HostName 43.161.196.57
  Port 22
  IdentityFile ~/.ssh/thehrz_server

Host al-hk-0
  User ecs-user
  HostName 8.218.181.38
  Port 2323
  IdentityFile ~/.ssh/thehrz_server

Host al-hz-0
  user ecs-user
  HostName 42.121.163.17
  Port 2233
  IdentityFile ~/.ssh/thehrz_server

Host al-light-hk-1
  user root
  HostName 47.243.218.152
  Port 22
  IdentityFile ~/.ssh/thehrz_server